# Generated by Django 5.0 on 2023-12-15 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogos',
            name='engine',
            field=models.CharField(choices=[('UNITY', 'Unity'), ('UNREAL 5', 'Unreal 5')], default='', max_length=100),
        ),
    ]
