# Generated by Django 5.0 on 2023-12-15 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0002_alter_jogos_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('legenda', models.CharField(max_length=150)),
                ('engine', models.CharField(choices=[('UNITY', 'Unity'), ('UNREAL 5', 'Unreal 5')], default='', max_length=100)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/')),
                ('publicada', models.BooleanField(default=False)),
                ('data_jogo', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
