# Generated by Django 5.0 on 2023-12-15 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0003_certificados'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificados',
            old_name='data_jogo',
            new_name='data_certificado',
        ),
    ]
