# Generated by Django 5.0 on 2023-12-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0005_jogos_link_jam_jogos_nome_curso_jogos_nome_jam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificados',
            name='engine',
            field=models.CharField(choices=[('Unity', 'Unity'), ('Unreal 5', 'Unreal 5')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='jogos',
            name='engine',
            field=models.CharField(choices=[('Unity', 'Unity'), ('Unreal 5', 'Unreal 5')], default='', max_length=100),
        ),
    ]
