# Generated by Django 5.0 on 2023-12-16 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0006_alter_certificados_engine_alter_jogos_engine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogos',
            name='nome_curso',
        ),
    ]
