# Generated by Django 5.0 on 2023-12-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0008_rename_imagem_jogos_imagem_capa'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogos',
            name='imagem_demo_1',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='jogos',
            name='imagem_demo_2',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='jogos',
            name='imagem_demo_3',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='jogos',
            name='imagem_demo_4',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/'),
        ),
    ]
