# Generated by Django 5.0 on 2023-12-17 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0009_jogos_imagem_demo_1_jogos_imagem_demo_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='hardSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('publicada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='quemSou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_inicial', models.CharField(max_length=100)),
                ('texto_final', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='softSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('publicada', models.BooleanField(default=False)),
            ],
        ),
    ]
