# Generated by Django 5.0 on 2023-12-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0010_hardskills_quemsou_softskills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quemsou',
            name='texto_final',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quemsou',
            name='texto_inicial',
            field=models.TextField(),
        ),
    ]
